package com.coachqa.entity;

// Generated Dec 21, 2014 1:45:02 PM by Hibernate Tools 3.4.0.CR1

import org.codehaus.jackson.map.ObjectMapper;

import java.io.IOException;
import java.io.StringWriter;
import java.io.Writer;

/**
 * Classroom generated by hbm2java
 */
public class Classroom implements java.io.Serializable {

	private Integer classroomId;
	private int minReputationToJoinId;
	private AppUser classOwner;
	private String className;
	public String description;
	private boolean isPublic;

	public Classroom() {
	}

	public Integer getClassroomId() {
		return this.classroomId;
	}

	public void setClassroomId(Integer classroomId) {
		this.classroomId = classroomId;
	}

	public int getMinReputationToJoinId() {
		return this.minReputationToJoinId;
	}

	public void setMinReputationToJoinId(int minReputationToJoinId) {
		this.minReputationToJoinId = minReputationToJoinId;
	}

	public AppUser getClassOwner() {
		return this.classOwner;
	}

	public void setClassOwner(AppUser classOwner) {
		this.classOwner = classOwner;
	}

	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

	public boolean isIsPublic() {
		return this.isPublic;
	}

	public void setIsPublic(boolean isPublic) {
		this.isPublic = isPublic;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public static void main(String[] args) {
		Classroom c = new Classroom();
		c.setClassName("Physics class");
		c.setIsPublic(true);
		c.setClassOwner(new AppUser(1, "email", "firstname", "middlename", "lastname"));

		ObjectMapper om = new ObjectMapper();
		om.writerWithDefaultPrettyPrinter();
		Writer w = new StringWriter();
		try {
			om.writeValue(w, c);
			System.out.println(w.toString());
		} catch (IOException e) {
			e.printStackTrace();
		}


	}
}
