package com.coachqa.entity;

// Generated Dec 21, 2014 1:45:02 PM by Hibernate Tools 3.4.0.CR1

/**
 * RefQuestionStatus generated by hbm2java
 */
public class RefQuestionStatus implements java.io.Serializable {

	private int refQuestionStatusId;
	private String questionStatusName;

	public RefQuestionStatus() {
	}

	public RefQuestionStatus(int refQuestionStatusId, String questionStatusName) {
		this.refQuestionStatusId = refQuestionStatusId;
		this.questionStatusName = questionStatusName;
	}

	public int getRefQuestionStatusId() {
		return this.refQuestionStatusId;
	}

	public void setRefQuestionStatusId(int refQuestionStatusId) {
		this.refQuestionStatusId = refQuestionStatusId;
	}

	public String getQuestionStatusName() {
		return this.questionStatusName;
	}

	public void setQuestionStatusName(String questionStatusName) {
		this.questionStatusName = questionStatusName;
	}

}
