package com.coachqa.entity;

// Generated Dec 21, 2014 1:45:02 PM by Hibernate Tools 3.4.0.CR1

/**
 * Tag generated by hbm2java
 */
public class Tag implements java.io.Serializable {

	private Integer tagId;
	private String tagName;
	private Integer noOfTaggedQuestions;
	private String tagDescription;

	public Tag(){}

	public Tag(int id, String name, String desc, int no) {
		tagId = id;
		tagName = name;
		tagDescription = desc ;
		noOfTaggedQuestions = no;
	}

	public String getTagDescription() {
		return tagDescription;
	}

	public void setTagDescription(String tagDescription) {
		this.tagDescription = tagDescription;
	}

	public Integer getNoOfTaggedQuestions() {
		return noOfTaggedQuestions;
	}

	public void setNoOfTaggedQuestions(Integer noOfTaggedQuestions) {
		this.noOfTaggedQuestions = noOfTaggedQuestions;
	}

	public Tag(String tagName) {
		this.tagName = tagName;
	}

	public Integer getTagId() {
		return this.tagId;
	}

	public void setTagId(Integer tagId) {
		this.tagId = tagId;
	}

	public String getTagName() {
		return this.tagName;
	}

	public void setTagName(String tagName) {
		this.tagName = tagName;
	}

}
