package com.coachqa.entity;

// Generated Dec 21, 2014 1:45:02 PM by Hibernate Tools 3.4.0.CR1

/**
 * UserReputation generated by hbm2java
 */
public class UserReputation implements java.io.Serializable {

	private int userReputationId;
	private String reputationName;

	public UserReputation() {
	}

	public UserReputation(int userReputationId, String reputationName) {
		this.userReputationId = userReputationId;
		this.reputationName = reputationName;
	}

	public int getUserReputationId() {
		return this.userReputationId;
	}

	public void setUserReputationId(int userReputationId) {
		this.userReputationId = userReputationId;
	}

	public String getReputationName() {
		return this.reputationName;
	}

	public void setReputationName(String reputationName) {
		this.reputationName = reputationName;
	}

}
