
spring:
  datasource:
    platform: "h2"
  datasource_oauth:
    driver: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/learnqa"
    username: "root"
    password: "root"
    initialSize: 10
    maxActive: 50
    maxWait: 1000

security:
  user:
    name: "anigam@expedia.com"
    password: "pass"
  oauth2:
    client:
      client-id: "foo"
      client-secret: "bar"
    authorization:
      checkTokenAccess: "isAuthenticated()"


#jmx properties
jmx:
  config:
    username: "admin"
    password: "admin"


database:
  config:
    driver: "com.mysql.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/learnqa"
    username: "root"
    password: "root"
    initialSize: 10
    maxActive: 50
    maxWait: 1000

