package com.coachqa.entity;

// Generated Dec 21, 2014 1:45:02 PM by Hibernate Tools 3.4.0.CR1


import javax.validation.constraints.NotNull;

/**
 * AppUser generated by hbm2java
 */
public class AppUser extends AccountEntity {

	private Integer appUserId;


	private Integer userReputationId;

	@NotNull
	private String email;

	private String password;

	@NotNull
	private String firstName;

	@NotNull
	private String middleName;

	private String lastName;

	private UserTypeEnum userType;

	public AppUser() {
	}

	public AppUser(String email, String password, String firstName,
				   String lastName) {
		this.email = email;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
	}

	public AppUser(Integer userReputationId, String email, String pasword,
				   String firstName, String middleName, String lastName) {
		this.userReputationId = userReputationId;
		this.email = email;
		this.password = pasword;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
	}

	public AppUser(int appUserId, String email, String firstName, String middleName, String lastName) {
		this.appUserId = appUserId;
		this.email = email;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
	}

	public Integer getAppUserId() {
		return this.appUserId;
	}

	public void setAppUserId(Integer appUserId) {
		this.appUserId = appUserId;
	}

	public Integer getUserReputationId() {
		return this.userReputationId;
	}

	public void setUserReputationId(Integer userReputationId) {
		this.userReputationId = userReputationId;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String pasword) {
		this.password = pasword;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public UserTypeEnum getUserType() {
		return userType;
	}

	public void setUserType(UserTypeEnum userType) {
		this.userType = userType;
	}


	public boolean equals(final Object o) {
		if (o == this) return true;
		if (!(o instanceof AppUser)) return false;
		final AppUser other = (AppUser) o;
		if (!other.canEqual((Object) this)) return false;
		final Object this$appUserId = this.getAppUserId();
		final Object other$appUserId = other.getAppUserId();
		if (this$appUserId == null ? other$appUserId != null : !this$appUserId.equals(other$appUserId)) return false;
		return true;
	}

	protected boolean canEqual(final Object other) {
		return other instanceof AppUser;
	}

	public int hashCode() {
		final int PRIME = 59;
		int result = 1;
		final Object $appUserId = this.getAppUserId();
		result = result * PRIME + ($appUserId == null ? 43 : $appUserId.hashCode());
		return result;
	}

	public String toString() {
		return "AppUser(appUserId=" + this.getAppUserId() + ", userReputationId=" + this.getUserReputationId() + ", email=" + this.getEmail() + ", password=" + this.getPassword() + ", firstName=" + this.getFirstName() + ", middleName=" + this.getMiddleName() + ", lastName=" + this.getLastName() + ", userType=" + this.getUserType() + ")";
	}
}
