package com.coachqa.entity;

// Generated Dec 21, 2014 1:45:02 PM by Hibernate Tools 3.4.0.CR1

/**
 * ClassroomMember generated by hbm2java
 */
@Deprecated
public class ClassroomMember implements java.io.Serializable {

	private Integer classroomMemberId;
	private int appUserId;
	private int classroomId;

	public ClassroomMember() {
	}

	public ClassroomMember(int appUserId, int classroomId) {
		this.appUserId = appUserId;
		this.classroomId = classroomId;
	}

	public Integer getClassroomMemberId() {
		return this.classroomMemberId;
	}

	public void setClassroomMemberId(Integer classroomMemberId) {
		this.classroomMemberId = classroomMemberId;
	}

	public int getAppUserId() {
		return this.appUserId;
	}

	public void setAppUserId(int appUserId) {
		this.appUserId = appUserId;
	}

	public int getClassroomId() {
		return this.classroomId;
	}

	public void setClassroomId(int classroomId) {
		this.classroomId = classroomId;
	}

}
