package com.coachqa.entity;

// Generated Dec 21, 2014 1:45:02 PM by Hibernate Tools 3.4.0.CR1

import com.coachqa.enums.QuestionLevelEnum;

import java.util.Collections;
import java.util.Date;
import java.util.List;

/**
 * Question generated by hbm2java
 */
public class Question extends Post implements java.io.Serializable {

	public Integer questionId;
	private Integer refSubjectId;
	private Integer questionLevelId;
	private Integer refQuestionStatusId;
	
	private String title;
	private byte[] image;
	
	private Integer noOfViews;
	private Date lastActiveDate;
	private Boolean isPublic;
	private Classroom classroom;

	public QuestionLevelEnum getQuestionLevelEnum() {
		return questionLevelEnum;
	}

	public void setQuestionLevelEnum(QuestionLevelEnum questionLevelEnum) {
		this.questionLevelEnum = questionLevelEnum;
	}

	private QuestionLevelEnum questionLevelEnum;

	public List<Integer> getTags() {
		return tags;
	}

	public void setTags(List<Integer> tags) {
		this.tags = tags;
	}

	private List<Integer> tags;


	private List<Answer> answers = Collections.emptyList();

	public Question() {
	}

	public Question(int refSubjectId, int questionLevelId, AppUser postedBy,
			int refQuestionStatusId, String title, String content,
			Date postDate, Date lastActiveDate, Boolean isPublic) {
		this.refSubjectId = refSubjectId;
		this.questionLevelId = questionLevelId;
		this.refQuestionStatusId = refQuestionStatusId;
		this.title = title;
		this.lastActiveDate = lastActiveDate;
		this.isPublic = isPublic;
	}

	public Question(int refSubjectId, int questionLevelId, AppUser postedBy,
			int refQuestionStatusId, String title, String content,
			Integer noOfViews, Date postDate, Date lastActiveDate,
			Integer votes, Boolean isPublic) {
		this.refSubjectId = refSubjectId;
		this.questionLevelId = questionLevelId;
		this.refQuestionStatusId = refQuestionStatusId;
		this.title = title;
		this.noOfViews = noOfViews;
		this.lastActiveDate = lastActiveDate;
		this.isPublic = isPublic;
	}

	public Integer getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(Integer questionId) {
		this.questionId = questionId;
	}

	public Integer getRefSubjectId() {
		return this.refSubjectId;
	}

	public void setRefSubjectId(Integer refSubjectId) {
		this.refSubjectId = refSubjectId;
	}

	public Integer getQuestionLevelId() {
		return this.questionLevelId;
	}

	public void setQuestionLevelId(Integer questionLevelId) {
		this.questionLevelId = questionLevelId;
	}


	public Integer getRefQuestionStatusId() {
		return this.refQuestionStatusId;
	}

	public void setRefQuestionStatusId(Integer refQuestionStatusId) {
		this.refQuestionStatusId = refQuestionStatusId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}


	public Integer getNoOfViews() {
		return this.noOfViews;
	}

	public void setNoOfViews(Integer noOfViews) {
		this.noOfViews = noOfViews;
	}


	public Date getLastActiveDate() {
		return this.lastActiveDate;
	}

	public void setLastActiveDate(Date lastActiveDate) {
		this.lastActiveDate = lastActiveDate;
	}


	public Boolean isIsPublic() {
		return this.isPublic;
	}

	public void setIsPublic(Boolean isPublic) {
		this.isPublic = isPublic;
	}

	public Boolean isPublic() {
		return isPublic;
	}

	public void setPublic(Boolean isPublic) {
		this.isPublic = isPublic;
	}

	public List<Answer> getAnswers() {
		return answers;
	}

	public void setAnswers(List<Answer> answers) {
		this.answers = answers;
	}

	public Classroom getClassroom() {
		return classroom;
	}

	public void setClassroom(Classroom classroom) {
		this.classroom = classroom;
	}


}
