package com.coachqa.entity;

// Generated Dec 21, 2014 1:45:02 PM by Hibernate Tools 3.4.0.CR1

/**
 * QuestionTag generated by hbm2java
 */
public class QuestionTag implements java.io.Serializable {

	private Integer questionTagId;
	private int questionId;
	private int tagId;

	public QuestionTag() {
	}

	public QuestionTag(int questionId, int tagId) {
		this.questionId = questionId;
		this.tagId = tagId;
	}

	public Integer getQuestionTagId() {
		return this.questionTagId;
	}

	public void setQuestionTagId(Integer questionTagId) {
		this.questionTagId = questionTagId;
	}

	public int getQuestionId() {
		return this.questionId;
	}

	public void setQuestionId(int questionId) {
		this.questionId = questionId;
	}

	public int getTagId() {
		return this.tagId;
	}

	public void setTagId(int tagId) {
		this.tagId = tagId;
	}

}
