package com.coachqa.entity;

// Generated Dec 21, 2014 1:45:02 PM by Hibernate Tools 3.4.0.CR1

import com.coachqa.enums.PostTypeEnum;
import com.coachqa.enums.QuestionLevelEnum;
import com.coachqa.enums.QuestionStatusEnum;


import java.util.Collections;
import java.util.Date;
import java.util.List;

/**
 * Question generated by hbm2java
 * NoOf View should be removed from questionin DB
 *
 */
public class Question extends Post implements java.io.Serializable {

	
	private Integer questionId;
	
	private Integer refSubjectId;
	
	private QuestionLevelEnum questionLevelEnum;
	
	private QuestionStatusEnum refQuestionStatusId;
	
	private String title;
	
	private Date lastActiveDate;

	
	private boolean publicQuestion;
	


	
	private List<Integer> tags = Collections.emptyList();
	
	private List<Answer> answers = Collections.emptyList();

	public Question() {
		setPostTypeEnum(PostTypeEnum.QUESTION);
	}

	public Integer getQuestionId() {
		return questionId;
	}

	public void setQuestionId(Integer questionId) {
		this.questionId = questionId;
	}

	public Integer getRefSubjectId() {
		return refSubjectId;
	}

	public void setRefSubjectId(Integer refSubjectId) {
		this.refSubjectId = refSubjectId;
	}

	public QuestionLevelEnum getQuestionLevelEnum() {
		return questionLevelEnum;
	}

	public void setQuestionLevelEnum(QuestionLevelEnum questionLevelEnum) {
		this.questionLevelEnum = questionLevelEnum;
	}

	public QuestionStatusEnum getRefQuestionStatusId() {
		return refQuestionStatusId;
	}

	public void setRefQuestionStatusId(QuestionStatusEnum refQuestionStatusId) {
		this.refQuestionStatusId = refQuestionStatusId;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Date getLastActiveDate() {
		return lastActiveDate;
	}

	public void setLastActiveDate(Date lastActiveDate) {
		this.lastActiveDate = lastActiveDate;
	}

	public boolean isPublicQuestion() {
		return publicQuestion;
	}

	public void setPublicQuestion(boolean publicQuestion) {
		this.publicQuestion = publicQuestion;
	}

	public List<Integer> getTags() {
		return tags;
	}

	public void setTags(List<Integer> tags) {
		this.tags = tags;
	}

	public List<Answer> getAnswers() {
		return answers;
	}

	public void setAnswers(List<Answer> answers) {
		this.answers = answers;
	}


}
