package com.coachqa.entity;

// Generated Dec 21, 2014 1:45:02 PM by Hibernate Tools 3.4.0.CR1

/**
 * AnswerComment generated by hbm2java
 */
public class AnswerComment implements java.io.Serializable {

	private Integer answerCommentId;
	private int answerId;
	private String answerComment;

	public AnswerComment() {
	}

	public AnswerComment(int answerId, String answerComment) {
		this.answerId = answerId;
		this.answerComment = answerComment;
	}

	public Integer getAnswerCommentId() {
		return this.answerCommentId;
	}

	public void setAnswerCommentId(Integer answerCommentId) {
		this.answerCommentId = answerCommentId;
	}

	public int getAnswerId() {
		return this.answerId;
	}

	public void setAnswerId(int answerId) {
		this.answerId = answerId;
	}

	public String getAnswerComment() {
		return this.answerComment;
	}

	public void setAnswerComment(String answerComment) {
		this.answerComment = answerComment;
	}

}
